# Generated by Django 5.1.3 on 2024-11-26 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_remove_task_created_at_task_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="due_time",
        ),
        migrations.AddField(
            model_name="task",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
